GOOGLE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "tajny-pravnik-bdvh",
  "private_key_id": "9f9aa3412f6269f1a67cd1d09f2988faa9129310",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEg8v2/9zfcoKA\nKVhqEsqBRHlEYDSMZbD64r8tDPfKgeUqVDqddUJdKzbgI26pY5aJWis1TeDF5F8Y\n...ZsAFPp8=\n-----END PRIVATE KEY-----\n",
  "client_email": "tajny-bot@tajny-pravnik-bdvh.iam.gserviceaccount.com",
  "client_id": "117321203722950121535",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/tajny-bot%40tajny-pravnik-bdvh.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

OPENAI_API_KEY = "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" 
