GOOGLE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "tajny-pravnik-bdvh",
  "private_key_id": "cf71d295b2b2447557daf71ed44ad376e6b4fb28",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nTVŮJ\\nCELÝ\\nKLÍČ\\n-----END PRIVATE KEY-----\\n",
  "client_email": "tajny-bot@tajny-pravnik-bdvh.iam.gserviceaccount.com",
  "client_id": "117321203722950121535",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/tajny-bot%40tajny-pravnik-bdvh.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

OPENAI_API_KEY = "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"
